---

- name: Install python tools
  dnf:
    pkg:
      - python3-virtualenv
    state: present
  tags:
    - python

- name: Install pyenv
  become: false
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ home_path }}/.pyenv"
  tags:
    - python

- name: Install pyenv virtualenv plugin
  become: false
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "{{ home_path }}/.pyenv/plugins/pyenv-virtualenv"
  tags:
    - python

- name: Install sbcl
  dnf:
    pkg:
      - sbcl
    state: present
  tags:
    - lisp
